### ISSUE TITLE
yml file url is invalid

### ISSUE THREAD

**Issue by mhearne-usgs** [barbagroup/numba_tutorial_scipy2016#1]
https://github.com/gforsyth/numba.tutorial.2016/environment.yml does not appear to exist. ??

**Comment by gforsyth** [comment]
Sorry, that's my bad. Need to update the link. You can grab the environment file here: https://github.com/barbagroup/numba_tutorial_scipy2016/blob/master/environment.yml

**Comment by gforsyth** [comment]
fixed in 38d7e5f (although the yml file is still corrupted)
